// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/wishlist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item_ItemPriority int32

const (
	Item_LOW  Item_ItemPriority = 0
	Item_MID  Item_ItemPriority = 50
	Item_HIGH Item_ItemPriority = 100
)

// Enum value maps for Item_ItemPriority.
var (
	Item_ItemPriority_name = map[int32]string{
		0:   "LOW",
		50:  "MID",
		100: "HIGH",
	}
	Item_ItemPriority_value = map[string]int32{
		"LOW":  0,
		"MID":  50,
		"HIGH": 100,
	}
)

func (x Item_ItemPriority) Enum() *Item_ItemPriority {
	p := new(Item_ItemPriority)
	*p = x
	return p
}

func (x Item_ItemPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Item_ItemPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_wishlist_proto_enumTypes[0].Descriptor()
}

func (Item_ItemPriority) Type() protoreflect.EnumType {
	return &file_proto_wishlist_proto_enumTypes[0]
}

func (x Item_ItemPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Item_ItemPriority.Descriptor instead.
func (Item_ItemPriority) EnumDescriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{0, 0}
}

type Item_ItemStatus int32

const (
	Item_INACTIVE Item_ItemStatus = 0
	Item_ACTIVE   Item_ItemStatus = 1
)

// Enum value maps for Item_ItemStatus.
var (
	Item_ItemStatus_name = map[int32]string{
		0: "INACTIVE",
		1: "ACTIVE",
	}
	Item_ItemStatus_value = map[string]int32{
		"INACTIVE": 0,
		"ACTIVE":   1,
	}
)

func (x Item_ItemStatus) Enum() *Item_ItemStatus {
	p := new(Item_ItemStatus)
	*p = x
	return p
}

func (x Item_ItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Item_ItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_wishlist_proto_enumTypes[1].Descriptor()
}

func (Item_ItemStatus) Type() protoreflect.EnumType {
	return &file_proto_wishlist_proto_enumTypes[1]
}

func (x Item_ItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Item_ItemStatus.Descriptor instead.
func (Item_ItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{0, 1}
}

type WishList_WishListStatus int32

const (
	WishList_INACTIVE WishList_WishListStatus = 0
	WishList_ACTIVE   WishList_WishListStatus = 1
)

// Enum value maps for WishList_WishListStatus.
var (
	WishList_WishListStatus_name = map[int32]string{
		0: "INACTIVE",
		1: "ACTIVE",
	}
	WishList_WishListStatus_value = map[string]int32{
		"INACTIVE": 0,
		"ACTIVE":   1,
	}
)

func (x WishList_WishListStatus) Enum() *WishList_WishListStatus {
	p := new(WishList_WishListStatus)
	*p = x
	return p
}

func (x WishList_WishListStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WishList_WishListStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_wishlist_proto_enumTypes[2].Descriptor()
}

func (WishList_WishListStatus) Type() protoreflect.EnumType {
	return &file_proto_wishlist_proto_enumTypes[2]
}

func (x WishList_WishListStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WishList_WishListStatus.Descriptor instead.
func (WishList_WishListStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{1, 0}
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WishListId string            `protobuf:"bytes,2,opt,name=wishListId,proto3" json:"wishListId,omitempty"`
	Name       string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Link       string            `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Price      float64           `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Priority   Item_ItemPriority `protobuf:"varint,6,opt,name=priority,proto3,enum=grpc.Item_ItemPriority" json:"priority,omitempty"`
	Status     Item_ItemStatus   `protobuf:"varint,7,opt,name=status,proto3,enum=grpc.Item_ItemStatus" json:"status,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wishlist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wishlist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetWishListId() string {
	if x != nil {
		return x.WishListId
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetPriority() Item_ItemPriority {
	if x != nil {
		return x.Priority
	}
	return Item_LOW
}

func (x *Item) GetStatus() Item_ItemStatus {
	if x != nil {
		return x.Status
	}
	return Item_INACTIVE
}

type WishList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status WishList_WishListStatus `protobuf:"varint,3,opt,name=status,proto3,enum=grpc.WishList_WishListStatus" json:"status,omitempty"`
}

func (x *WishList) Reset() {
	*x = WishList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wishlist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WishList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishList) ProtoMessage() {}

func (x *WishList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wishlist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishList.ProtoReflect.Descriptor instead.
func (*WishList) Descriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{1}
}

func (x *WishList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WishList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WishList) GetStatus() WishList_WishListStatus {
	if x != nil {
		return x.Status
	}
	return WishList_INACTIVE
}

type CreateWishListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WishList *WishList `protobuf:"bytes,1,opt,name=wishList,proto3" json:"wishList,omitempty"`
}

func (x *CreateWishListReq) Reset() {
	*x = CreateWishListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wishlist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWishListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWishListReq) ProtoMessage() {}

func (x *CreateWishListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wishlist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWishListReq.ProtoReflect.Descriptor instead.
func (*CreateWishListReq) Descriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWishListReq) GetWishList() *WishList {
	if x != nil {
		return x.WishList
	}
	return nil
}

type CreateWishListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WishListId string `protobuf:"bytes,1,opt,name=wishListId,proto3" json:"wishListId,omitempty"`
}

func (x *CreateWishListResp) Reset() {
	*x = CreateWishListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wishlist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWishListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWishListResp) ProtoMessage() {}

func (x *CreateWishListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wishlist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWishListResp.ProtoReflect.Descriptor instead.
func (*CreateWishListResp) Descriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWishListResp) GetWishListId() string {
	if x != nil {
		return x.WishListId
	}
	return ""
}

type AddItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *AddItemReq) Reset() {
	*x = AddItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wishlist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemReq) ProtoMessage() {}

func (x *AddItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wishlist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemReq.ProtoReflect.Descriptor instead.
func (*AddItemReq) Descriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{4}
}

func (x *AddItemReq) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddItemResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId string `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
}

func (x *AddItemResp) Reset() {
	*x = AddItemResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wishlist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResp) ProtoMessage() {}

func (x *AddItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wishlist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResp.ProtoReflect.Descriptor instead.
func (*AddItemResp) Descriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{5}
}

func (x *AddItemResp) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type ListWishListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WishListId string `protobuf:"bytes,1,opt,name=wishListId,proto3" json:"wishListId,omitempty"`
}

func (x *ListWishListReq) Reset() {
	*x = ListWishListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wishlist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWishListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWishListReq) ProtoMessage() {}

func (x *ListWishListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wishlist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWishListReq.ProtoReflect.Descriptor instead.
func (*ListWishListReq) Descriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{6}
}

func (x *ListWishListReq) GetWishListId() string {
	if x != nil {
		return x.WishListId
	}
	return ""
}

type ListWishListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListWishListResp) Reset() {
	*x = ListWishListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wishlist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWishListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWishListResp) ProtoMessage() {}

func (x *ListWishListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wishlist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWishListResp.ProtoReflect.Descriptor instead.
func (*ListWishListResp) Descriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{7}
}

func (x *ListWishListResp) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_wishlist_proto protoreflect.FileDescriptor

var file_proto_wishlist_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0xac, 0x02, 0x0a,
	0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x69, 0x73, 0x68, 0x4c,
	0x69, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e,
	0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x52, 0x08,
	0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2a, 0x0a, 0x0c, 0x49, 0x74, 0x65, 0x6d, 0x50,
	0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x4f, 0x57, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x4d, 0x49, 0x44, 0x10, 0x32, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x49, 0x47,
	0x48, 0x10, 0x64, 0x22, 0x26, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x22, 0x91, 0x01, 0x0a, 0x08,
	0x57, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x57, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x57, 0x69, 0x73,
	0x68, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x2a, 0x0a, 0x0e, 0x57, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56,
	0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x22,
	0x3f, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x08, 0x77, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x69,
	0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x08, 0x77, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x34, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x69, 0x73, 0x68, 0x4c, 0x69,
	0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x69, 0x73, 0x68,
	0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04,
	0x69, 0x74, 0x65, 0x6d, 0x22, 0x25, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x57, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1e,
	0x0a, 0x0a, 0x77, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x77, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x34,
	0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x20, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x32, 0xb1, 0x01, 0x0a, 0x0f, 0x57, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x57, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x10, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x35, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x73, 0x68,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x6d, 0x65, 0x6f, 0x41, 0x6d, 0x61, 0x7a,
	0x6f, 0x6e, 0x61, 0x73, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_wishlist_proto_rawDescOnce sync.Once
	file_proto_wishlist_proto_rawDescData = file_proto_wishlist_proto_rawDesc
)

func file_proto_wishlist_proto_rawDescGZIP() []byte {
	file_proto_wishlist_proto_rawDescOnce.Do(func() {
		file_proto_wishlist_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_wishlist_proto_rawDescData)
	})
	return file_proto_wishlist_proto_rawDescData
}

var file_proto_wishlist_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_wishlist_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_wishlist_proto_goTypes = []interface{}{
	(Item_ItemPriority)(0),       // 0: grpc.Item.ItemPriority
	(Item_ItemStatus)(0),         // 1: grpc.Item.ItemStatus
	(WishList_WishListStatus)(0), // 2: grpc.WishList.WishListStatus
	(*Item)(nil),                 // 3: grpc.Item
	(*WishList)(nil),             // 4: grpc.WishList
	(*CreateWishListReq)(nil),    // 5: grpc.CreateWishListReq
	(*CreateWishListResp)(nil),   // 6: grpc.CreateWishListResp
	(*AddItemReq)(nil),           // 7: grpc.AddItemReq
	(*AddItemResp)(nil),          // 8: grpc.AddItemResp
	(*ListWishListReq)(nil),      // 9: grpc.ListWishListReq
	(*ListWishListResp)(nil),     // 10: grpc.ListWishListResp
}
var file_proto_wishlist_proto_depIdxs = []int32{
	0,  // 0: grpc.Item.priority:type_name -> grpc.Item.ItemPriority
	1,  // 1: grpc.Item.status:type_name -> grpc.Item.ItemStatus
	2,  // 2: grpc.WishList.status:type_name -> grpc.WishList.WishListStatus
	4,  // 3: grpc.CreateWishListReq.wishList:type_name -> grpc.WishList
	3,  // 4: grpc.AddItemReq.item:type_name -> grpc.Item
	3,  // 5: grpc.ListWishListResp.items:type_name -> grpc.Item
	5,  // 6: grpc.WishListService.Create:input_type -> grpc.CreateWishListReq
	7,  // 7: grpc.WishListService.Add:input_type -> grpc.AddItemReq
	9,  // 8: grpc.WishListService.List:input_type -> grpc.ListWishListReq
	6,  // 9: grpc.WishListService.Create:output_type -> grpc.CreateWishListResp
	8,  // 10: grpc.WishListService.Add:output_type -> grpc.AddItemResp
	10, // 11: grpc.WishListService.List:output_type -> grpc.ListWishListResp
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_wishlist_proto_init() }
func file_proto_wishlist_proto_init() {
	if File_proto_wishlist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_wishlist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wishlist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WishList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wishlist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWishListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wishlist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWishListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wishlist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wishlist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wishlist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWishListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wishlist_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWishListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_wishlist_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wishlist_proto_goTypes,
		DependencyIndexes: file_proto_wishlist_proto_depIdxs,
		EnumInfos:         file_proto_wishlist_proto_enumTypes,
		MessageInfos:      file_proto_wishlist_proto_msgTypes,
	}.Build()
	File_proto_wishlist_proto = out.File
	file_proto_wishlist_proto_rawDesc = nil
	file_proto_wishlist_proto_goTypes = nil
	file_proto_wishlist_proto_depIdxs = nil
}
